name: Output
on:
    workflow_dispatch:
    repository_dispatch:
      types: [run-tests, deploy-to-prod]  # Optional filtering
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Show the github context
        run: echo "${{ toJSON(github) }}"
