name: Output
on:
    repository_dispatch:
      types: [run-tests, deploy-to-prod]  # Optional filtering
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Show the github context
        run: echo "${{ toJSON(github) }}"
      - name: Print event type
        run: |
            echo "Event type: ${{ github.event.action }}"
